import type { Metadata } from "next";
import { poppins, montserrat } from "./fonts/fonts";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import Header from "@/components/Header";
import Sidebar from "@/components/Sidebar";
import GoBackButton from "@/components/GoBackButton";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${poppins.variable} ${montserrat.variable} font-primary antialiased`}
        >
          <Header />
          <div className="flex min-h-screen">
            <Sidebar />

            <div className="flex-1 p-3 bg-accent-foreground/20 overflow-y-auto">
              {children}
            </div>
          </div>
        </body>
      </html>
    </ClerkProvider>
  );
}
